version: '3'

services:
  spring-boot-starter-parent:
    image: spring-boot-starter-parent:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod