version: '3.9'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
